apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-action
  labels:
    app: demo-action
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-action
  template:
    metadata:
      labels:
        app: demo-action
    spec:
      containers:
      - image: 885300287765.dkr.ecr.us-east-1.amazonaws.com/ecr-repo:IMAGE_LABEL
        name: demo-action
        imagePullPolicy: Always
        args: ["npm", "start"]
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "250Mi"
            cpu: "250m"
          limits:
              memory: "500Mi"
              cpu: "500m"

